version: '3.9'

services:
  web:
    build: .
    expose:
      - "8000"
    container_name: django_app
    command: >
      sh -c "
      ln -sf /usr/lib/x86_64-linux-gnu/libgdal.so.36 /usr/lib/libgdal.so &&
      ldconfig &&
      gunicorn Finalproject.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --workers 4 --threads 20 --worker-class gthread
      "
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - AI_SERVER_URL=http://ai_server:8080
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
      - ai_server

  ai_server:
    build: ./ai_server
    container_name: ai_server
    expose:
      - "8080"
    environment:
      - TZ=Asia/Seoul
      - MODEL_PATH=/app/models/qwen_finetuned.Q8_0.gguf
      - N_GPU_LAYERS=0
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 2
    volumes:
      - ./ai_server:/app
      - ./학습했던코드:/app/models
      - /etc/localtime:/etc/localtime:ro


  cron:
    build: .
    container_name: django_cron
    command: >
      sh -c "
      ln -sf /usr/lib/x86_64-linux-gnu/libgdal.so.36 /usr/lib/libgdal.so &&
      ldconfig &&
      while true; do
        echo \"Running scheduled tasks at $$(date)... \";
        python manage.py fetch_all_data;
        sleep 300;
      done
      "
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.4
    container_name: postgres_emergency
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    expose:
      - "6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro


  nginx:
    image: nginx:latest
    container_name: backend_nginx
    depends_on:
      - web
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
  static_volume: